module: MIDISynth
author: Gene De Lisa
author_url: http://rockhoppertech.com/blog/
github_url: http://github.com/genedelisa/MIDISynth
copyright: "2016 © Gene De Lisa. See LICENSE for more details. [Rockhopper Technologies](http://rockhoppertech.com/)"
min_acl: private
clean: true
readme: ./README.md
output: docs/swiftDocs
sdk: iphone

# swift_version: 4.0
# xcodebuild-arguments: -scheme,MIDISynth


