# file: .travis.yml
language:objective-c
osx_image:xcode9.2
xcode_project:MIDISynth
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- brew install swiftlint || true
- gem install xcpretty -N

script:
    - set -o pipefail

    - bundle exec fastlane ios test

#    - xctool -project MIDISynth.xcodeproj  -scheme "MIDISynth" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" ONLY_ACTIVE_ARCH=NO test | xcpretty -c

    - swiftlint

    - yarn danger

#    - xctool -project MIDISynth.xcodeproj  -scheme "MIDISynth" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" ONLY_ACTIVE_ARCH=NO test | xcpretty -c

# - xcodebuild -scheme MIDISynth -project MIDISynth.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test


after_success:
- bash <(curl -s https://codecov.io/bash)


# http://docs.travis-ci.com/user/languages/objective-c/
